### ISSUE TITLE
cssQuestion 1

### ISSUE THREAD

**Issue by geyalan** [geyalan/cssQuestion#1]
1、下面这个图形，只使用一个标签，可以有多少种实现方式：
![这里写图片描述](http://images.cnblogs.com/cnblogs_com/coco1s/881614/o_border.png)
假设我们的单标签是div：
``` html
<div></div>
```
定义如下css：
``` css
div{
	position:relative;
	width:200px;
	height:60px;
	background:#ddd;
}
```
</br>
**方法1：通过border实现**
这个应该是最容易想到了
``` css
div{
	border-left:5px solid #deeppink;
}
```
</br>
**方法二：利用伪类实现**
本题可以利用伪类元素轻松实现
``` css
div::after{
	position:absolute;
	content:'';
	width:5px;
	height:60px;
	left:0;
	top:0;
	background:deeppink;
}
```
</br>
**方法三：外box-shadow**
盒阴影 `box-shadow` 大部分人只是用来生成阴影，其实阴影可以有单侧阴影、多重阴影、阴影不虚化，这就需要去了解 `box-shadow` 每个参数的具体作用。

```
div{
	box-shadow:-5px 0px 0 0 deeppink;
}
```
</br>
**方法四：内box-shadow**
盒阴影还有一个参数inset，用于设置内阴影，也可以完成该效果：

```
div{
	box-shadow:inset 5px 0px 0 0 deeppink;
}
```
</br>
**方法五：drop-shadow**
 drop-shadow是css3新滤镜filter中的一个滤镜，也可以生成阴影，不过它的参数只有3个，比box-shadow少一个。
 

```

div{
	filter:drop-shadow(-5px 0 0 deeplink);
}
```
</br>
**方法六：渐变**
灵活使用 CSS3 的渐变可以完成大量想不到的图形，CSS3 的渐变简单而言分为线性渐变和径向渐变，本题使用线性渐变，可以轻易解题：

```
div{
	 background-image:linear-gradient(90deg, deeppink 0px, deeppink 5px, transparent 5px);
}
```
</br>
**方法七：轮廓outline**
这个用的比较少，outline （轮廓）是绘制于元素周围的一条线，位于边框边缘的外围，可起到突出元素的作用。这个方法算是下下之选。

```
div{
	height:50px;
	outline:5px solid #deplink;
}
div::after{
	position:absolute;
	content:'';
	top:-5px;
	bottom:-5px;
	right:-5px;
	left:0px;
	background:#ddd;
}
```
</br>
**方法八：滚动条**
通过改变滚动条样式实现

```
div{
	width:205px;
	background:deeplink;
	overflow-y:scroll;
}
div::-webkit-scrollbar{
	width:200px;
	background-color:#ddd;
}
```
